# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Fardos.dev"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by Fardos.dev "
footer:
 name: "Hey there, my name is fardos"
 bio: "I am a developer and a tech aficionado from.... Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free?"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/"
  github: "https://www.github.com/"

theme: jekyll-theme-cayman
